# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Saurabh Tiwari
tagline:          0b101010
url:              http://www.neo7.in
paginate:         1
baseurl:          /
author:
  name:           Saurabh Tiwari
  url:            https://twitter.com/saurtiwa
  email:          tsaurabh.in@gmail.com

# Custom vars
version:          1.0.1
github:
  repo:           https://github.com/neo7/brine
