# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Saurabh Tiwari
tagline:          'neo7'
description:      'Philosopher, Software Developer, Linuxer, Happiness Seeker.'


url:              http://www.neo7.in
baseurl:          /

author:
  name:           'Saurabh Tiwari'
  url:            https://twitter.com/saurtiwa

paginate:        1 

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/neo7/brine
